### ISSUE TITLE
Error on install and fails to load

### ISSUE THREAD

**Issue by aurel-g** [NyaamZ/efficiency-nodes-ED#4]
Hi,

I use the current version of ComfyUI with Python 3.11. I installed ComfyUI's requirements + tsc_utils

When attempting to execute install.py, I got this error :

`[ERROR] efficiency nodes ED: An error occurred while annotating the file.`

then, when attempting to load the module in comfyui: 

```

Launching ComfyUI from: /mnt/comfyui/app

Total VRAM 16073 MB, total RAM 32000 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /mnt/comfyui/app/web
Traceback (most recent call last):
  File "/mnt/comfyui/app/nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/mnt/comfyui/app/custom_nodes/efficiency-nodes-ED/__init__.py", line 16, in <module>
    from  .efficiency_nodes_ED import NODE_CLASS_MAPPINGS
  File "/mnt/comfyui/app/custom_nodes/efficiency-nodes-ED/efficiency_nodes_ED.py", line 49, in <module>
    from bnk_adv_encode import AdvancedCLIPTextEncode
ModuleNotFoundError: No module named 'bnk_adv_encode'

Cannot import /mnt/comfyui/app/custom_nodes/efficiency-nodes-ED module for custom nodes: No module named 'bnk_adv_encode'

Import times for custom nodes:
   0.0 seconds: /mnt/comfyui/app/custom_nodes/websocket_image_save.py
   0.0 seconds (IMPORT FAILED): /mnt/comfyui/app/custom_nodes/efficiency-nodes-ED

Starting server

To see the GUI go to: http://0.0.0.0:8080

```

**Comment by NyaamZ** [comment]
[Efficiency Nodes for ComfyUI](https://github.com/jags111/efficiency-nodes-comfyui) is MUST required.
